#!/bin/bash
# by Dominik Stanisław Suchora <hexderm@gmail.com>
# License: GNU GPLv3

shopt -s extglob

declare api_key="E8Uh5l5fHZ6gD8U3KycjAIAk46f68Zw7C6eW8WSjZvCLXebZ7p0r1yrYDrLilk2F" user_agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.2 Chrome/87.0.4280.144 Safari/537.36"

ucurl() {
    curl -L -g -s --user-agent "$user_agent" -H 'Accept-Encoding: gzip, deflate' --compressed "$@"
}

declare -r DOMAIN="https://disqus.com/api/3.0"
declare limit=100 t1 t2

discussion_get() {
    local next i='1'
    ucurl "$DOMAIN/threads/details?thread=slug%3A$2&forum=$1&attach=topics&related=forum&api_key=$api_key" > "details.json"
    grep -q '{"code":2,"response":"Invalid argument,' 'details.json' && { rm 'details.json'; return; }
    local -r thread_id="$(jq -r '.response.id' "details.json")"
    while :
    do
        ucurl "$DOMAIN/threads/listPostsThreaded?limit=$limit&thread=$thread_id&forum=$1&order=popular&cursor=$next&api_key=$api_key" > "$i.json"
        echo "$i.json"
        next="$(jq -r '.cursor.id' "$i.json")"
        [ "$(jq '.cursor.hasNext' "$i.json")" != "true" ] && break
        ((i++))
    done
}

user_get() {
    local i j next name
    ucurl "$DOMAIN/users/details?user=username%3A$1&attach=userFlaggedUser&api_key=$api_key" > 'details.json'
    grep -q '{"code":2,"response":"Invalid argument,' 'details.json' && { rm 'details.json'; return; }
    echo 'details.json'
    grep -q ',"isPrivate":true,"' 'details.json' && return
    ucurl "$DOMAIN/users/listMostActiveForums?user=username%3A$1&limit=$limit&api_key=$api_key" > 'mostactiveforums.json'
    echo 'mostactiveforums.json'
    for j in 'favorites;timelines/activities?type=profile&index=favorites&target=user%3Ausername%3A' 'comments;timelines/activities?type=profile&index=comments&target=user%3Ausername%3A' 'threads;timelines/activities?type=profile&index=threads&target=user%3Ausername%3A' 'followingchannels;users/listFollowingChannels?order=desc&user=username%3A' 'badges;badges/awarded?user=username%3A'
    do
        i='1'
        while :
        do
            name="${j%%;*}-$i.json"
            ucurl "$DOMAIN/${j#*;}$1&cursor=$next&limit=$limit&api_key=$api_key" > "$name"
            echo "$name"
            next="$(jq -r '.cursor.id' "$name")"
            [ "$(jq '.cursor.hasNext' "$name")" != "true" ] && break
            ((i++))
        done
        next=''
    done
}

owner_get() {
    local g='1' i next
    ucurl "$DOMAIN/forums/details?forum=$1&attach=forumFeatures&api_key=$api_key" > "forumfeatures.json"
    grep -q '{"code":2,"response":"Invalid argument,' 'forumfeatures.json' && { rm 'forumfeatures.json'; return; }
    while :
    do
        ucurl "$DOMAIN/timelines/activities?type=profile&target=forum%3A$1&cursor=$next&limit=$limit&api_key=$api_key" > "$g.json"
        echo "$g.json"
        for i in $(jq -r '.response.objects | to_entries | .[].value.slug | select( . != null )' "$g.json")
        do
            mkdir "$i" || continue
            cd "$i" || continue
            echo "$i"
            discussion_get "$1" "$i"
            cd '..'
        done
        next="$(jq -r '.cursor.id' "$g.json")"
        [ "$(jq '.cursor.hasNext' "$g.json")" != "true" ] && break
        ((g++))
    done
}

usage() {
    printf '%s [DIR] [URL]...\n' "${0##*/}"
}

[ "$#" -lt '2' ] && { usage >&2; exit 1; }
cd "$1" || { usage >&2; exit 1; }
shift

while [ "$#" -gt 0 ]
do
    case "$1" in
        +([[:alnum:]_-])?([/]))
            owner_get "${1%/}";;
        http?(s)://disqus.com/home/forum/+([[:alnum:]_-])[/])
            t1="${1#http*://disqus.com/home/forum/}"
            owner_get "${t1%/}";;
        +([[:alnum:]_-])/+([[:alnum:]_-]))
            discussion_get "${1%/*}" "${1#*/}";;
        http?(s)://disqus.com/home/discussion/+([[:alnum:]_-])/+([[:alnum:]_-])[/])
            t1="${1#http*://disqus.com/home/discussion/}"
            t2=${t1%/}
            discussion_get "${t2%/*}" "${t2#*/}";;
        @+([[:alnum:]_-]))
            user_get "${1#@}";;
        http?(s)://disqus.com/by/+([[:alnum:]_-])[/])
            t1="${1#http*://disqus.com/by/}"
            user_get "${t1%/}";;
        #http[s]://+(+([[:alnum:]]).)+([[:alpha:]])/*)
    esac
    shift
done
